FROM python:3
ARG USER_HOME=/usr/local/app/
WORKDIR ${USER_HOME}
COPY . ${USER_HOME}
RUN apt-get update && apt-get install -y gcc unixodbc-dev

# RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
# RUN curl https://packages.microsoft.com/config/ubuntu/21.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
# RUN apt-get update
# RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17
# RUN ACCEPT_EULA=Y apt-get install -y mssql-tools
# RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
# RUN . ~/.bashrc

# RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install -r requirements.txt
# RUN apt-get install python3-pymysql
RUN pip3 install mysqlclient==2.0.1
RUN python3 manage.py makemigrations
RUN python3 manage.py migrate
ENTRYPOINT ["python3","manage.py","runserver", "0.0.0.0:8000"]
EXPOSE 8000