# Generated by Django 3.2.3 on 2022-12-05 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_page_clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(default='', max_length=10)),
                ('deviceID', models.CharField(default='', max_length=40)),
                ('session_id', models.CharField(default='', max_length=40)),
                ('landing_page', models.CharField(default='0', max_length=40)),
                ('rmi_page', models.CharField(default='0', max_length=40)),
                ('iom_page', models.CharField(default='0', max_length=40)),
                ('t_page', models.CharField(default='0', max_length=40)),
                ('pmf_page', models.CharField(default='0', max_length=40)),
                ('smf_page', models.CharField(default='0', max_length=40)),
                ('rc_page', models.CharField(default='0', max_length=40)),
                ('wc_page', models.CharField(default='0', max_length=40)),
                ('carbon_offset', models.CharField(default='0', max_length=40)),
                ('watchlist', models.CharField(default='0', max_length=40)),
                ('feedback', models.CharField(default='0', max_length=40)),
                ('about', models.CharField(default='0', max_length=40)),
                ('tutorial', models.CharField(default='0', max_length=40)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='device_session_chart_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(default='', max_length=10)),
                ('deviceID', models.CharField(default='', max_length=40)),
                ('session_id', models.CharField(default='', max_length=40)),
                ('chart', models.CharField(default='', max_length=30)),
                ('visits', models.IntegerField()),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='customer_table',
            name='emailID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session_page_usage_new',
            name='rc_page',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='session_page_usage_new',
            name='wc_page',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
